### ISSUE TITLE
Beni culturali pagina non trovata

### ISSUE THREAD

**Issue by GaetanoRu** [italia/awesome-italian-public-datasets#13]
Il link [Beni culturali](https://github.com/italia/awesome-italian-public-datasets/blob/d15f28287faa60f608f8710f65b0875a438572cf/README.md?plain=1#L38) rimanda un 404

**Comment by giorgialodi** [comment]
Il Ministero raccoglie i suoi dati aperti in [dati.cultura.gov.it](https://dati.cultura.gov.it/) @bfabio
