### ISSUE TITLE
Rivedere link

### ISSUE THREAD

**Issue by thistlillo** [italia/awesome-italian-public-datasets#17]
Anche se non si puo` non notare che le segnalazioni di broken links vengono ignorate, nella speranza che questo non sia il solito progetto pubblico italiano, avviato mezzo completato e poi abbandonato, vi segnalo che:

seguendo una buona parte dei link a risorse pubbblicati, prima o poi, si raggiunge un "file non trovato".

**Comment by bfabio** [comment]
Prendiamo come riferimento #18 che ha la lista dei link rotti, chiudo l'issue.
