### ISSUE TITLE
Link Non Piu Validi 

### ISSUE THREAD

**Issue by APXc** [italia/awesome-italian-public-datasets#18]
Di seguito segnalo che i link i quali portano ad pagine di errore o di NotFound (almeno alla data in cui apro questa segnalazione):
-  Regioni e città:   http://estratti.openstreetmap.it/ => Non Piu Raggiungibile 
- Trasporti : http://www.sviluppoeconomico.gov.it/index.php/it/open-data/elenco-dataset/2032336-carburanti-prezzi-praticati-e-anagrafica-degli-impianti => Non Piu Raggiungibile 
-   Trasporti : http://dati.mit.gov.it/catalog/dataset/parco-circolante-dei-veicoli => Not Found 
-  Governo e Settore Pubblico : http://www.cantieriscuole.it/open_data.aspx =>  Non Piu Raggiungibile 
- Governo e Settore Pubblico : [MISE: Aiuti di Stato](http://www.sviluppoeconomico.gov.it/index.php/it/open-data/elenco-dataset) => Non Piu Raggiungibile 
- Public Administration Use Cases : http://opencantieri.mit.gov.it/ =>Non Piu Raggiungibile 
- Public Administration Use Cases :  https://www.opencivitas.it/ =>Non Piu Raggiungibile 
- Public Administration Use Cases : https://opencup.gov.it/it/opendata  =>Non Piu Raggiungibile 
- Public Administration Use Cases : https://openregio.it/ => 523 : Origin is unreachable
- Public Administration Use Cases :  http://opentransport.mit.gov.it/ =>Non Piu Raggiungibile

**Comment by bfabio** [comment]
Grazie @APXc. Il primo link rotto è risolto da #19

**Comment by giorgialodi** [comment]
Ciao a tutti, a parte il primo link che è già risolto suggerirei di agire così @bfabio:

2) Carburanti e Prezzi Praticati - https://www.mimit.gov.it/it/open-data/elenco-dataset/carburanti-prezzi-praticati-e-anagrafica-degli-impianti
3) parco circolante dei veicoli: https://dati.mit.gov.it/catalog/dataset/dataset-parco-circolante-dei-veicoli
4) Cantieri scuole lo eliminerei 
5) Forse lo eliminerei
6) Open Cantieri mi sembra non esista più ma ho trovato questo https://osservacantieri.mit.gov.it/ poi ci sono gli open data del ministero. 
7) OpenCivitas mi sembra raggiungibile. Se si vuole mettere la sezione specifica open data - https://www.opencivitas.it/open-data
8) OpenCup —> https://www.opencup.gov.it/portale/web/opencup/opendata
9) Open Regio —> https://openregio.anbsc.it/
10) Non vedo più qualcosa di significativo. Forse il portale open data del ministero ma quello è troppo generico, lascerei stare.

My2cents
