### ISSUE TITLE
💡 Add this project to awesome-italia-opensource

### ISSUE THREAD

**Issue by FabrizioCafolla** [italia/awesome-italian-public-datasets#25]
I founded Italia Open-source, a community that aims to share and grow the Italian open-source world, but more generally to highlight Italian tech excellence.

Our website [italiaopensource.com](https://italiaopensource.com/) is based on open data that reside on the [awesome-italia-opensource](https://github.com/italia-opensource/awesome-italia-opensource) repository, you can add your own open-source project, community tech(s), and much more. All through a simple pull request, you can add your data.

**Comment by bfabio** [comment]
Hi @FabrizioCafolla, thanks for your proposal.

If you'd like to add your project to the awesome-italia-opensource repository, we encourage you to submit the pull request yourself. We have no objections to including your project, but as the owner, it would be most appropriate for you to handle this part.
