### ISSUE TITLE
Citare/linkare le risorse open utilizzate/prodotte dai progetti segnalati

### ISSUE THREAD

**Issue by mfortini** [italia/awesome-italian-public-datasets#6]
Penso che una citazione permetterebbe sia di spiegare come il progetto sia significativo e nello stesso tempo darebbe valore ai dati che usa.

**Comment by dagoneye** [comment]
+1 per il suggerimento di @mfortini. Visto che non sono più semplici link come nel caso dei dati sopra, si potrebbe pensare di racchiudere i progetti in una tabella? 

Mi viene in mente una cosa tipo:

| Progetto civico  | Descrizione | Dati aperti usati | Dati aperti creati |
| ----------------| ------------- | ----------------| ------------- |  
| [Terremoto Centro Italia](https://terremotocentroitalia.info/about/) | progetto nato per condividere informazioni utili e verificate sugli eventi sismici che hanno coinvolto il centro Italia durante il 2016 e il 2017 | | |
 
A tendere potrebbe essere utile per vedere se potrebbe nascere un incrocio tra offerta e riuso dei dati ed evolvere la lista...

**Comment by mariaclaudia** [comment]
@dagoneye @mfortini ottima idea quella di organizzare i dati in questo modo, procedete pure con PR grazie
